<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\EnhancedApiSearch\Plugin;

use Magento\Framework\Webapi\Rest\Request;

class InterceptParametersResolution
{
    /**
     * @param Request $request
     * @return void
     */
    public function beforeGetRequestData(Request $request): void
    {
        /**
         * Let's override only the GET requests.
         * Current implementation of searchCriteria only occurs on GET requests.
         */
        if (!$request->isGet()) {
            return;
        }

        /**
         * Now, let's check if body has parameters. If not, just return the original method.
         */
        $bodyParams = $request->getBodyParams();
        if (empty($bodyParams['searchCriteria'])) {
            return;
        }

        /**
         * If everything is valid, then set body parameters over querystring parameters.
         * Trying to merge them can lead to a mistyped error, for instance, if both has 'pageSize' it would result in:
         * 'searchCriteria' => [
         *     'pageSize' => [
         *         20,
         *         40
         *     ]
         * ]
         * This would break the application because pageSize parameter is supposed to be an integer, not an array.
         */
        $request->setParams($bodyParams);
    }
}
